_wandb:
    value:
        cli_version: 0.21.3
        e:
            u60qyrb851j5ff0ofxpr0q6rau98ik84:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 40
                cpu_count_logical: 80
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "471321321472"
                        used: "332424384512"
                email: utsunomiya@mdl.cs.tsukuba.ac.jp
                executable: /home/utsu/sp/.venv/bin/python
                git:
                    commit: c6a799c262c61600f50f28be40adb13cc521e0c8
                    remote: https://github.com/kodai-utsunomiya-mdl/spurious-feature-analysis.git
                gpu: Tesla V100-SXM2-16GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "17179869184"
                      name: Tesla V100-SXM2-16GB
                      uuid: GPU-291344de-fc60-b6a3-0720-452cf3268554
                host: 0be0b5f5d7a5
                memory:
                    total: "540905930752"
                os: Linux-5.4.0-193-generic-x86_64-with-glibc2.39
                program: /home/utsu/sp/main.py
                python: CPython 3.12.11
                root: /home/utsu/sp
                startedAt: "2025-09-10T09:36:17.471774Z"
                writerId: u60qyrb851j5ff0ofxpr0q6rau98ik84
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.12.11
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
activation_function:
    value: relu
analysis_epochs:
    value:
        - 10
        - 15
        - 20
        - 25
        - 30
        - 35
        - 40
        - 45
        - 50
        - 55
        - 60
        - 65
        - 70
        - 75
        - 80
        - 85
        - 90
        - 95
        - 100
        - 110
        - 120
        - 130
        - 150
        - 200
        - 250
        - 300
        - 400
        - 500
        - 600
        - 700
        - 1000
        - 2000
        - 3000
        - 4000
        - 5000
        - 6000
        - 7000
        - 8000
        - 10000
        - 12000
        - 14000
        - 16000
        - 18000
        - 20000
analysis_target:
    value: both
analyze_activation_singular_values:
    value: false
analyze_barycentric_alignment:
    value: false
analyze_barycentric_distance:
    value: false
analyze_bregman_divergence:
    value: false
analyze_conditional_distance:
    value: true
analyze_intergroup_distance:
    value: true
analyze_logit:
    value: false
analyze_mutual_information:
    value: false
analyze_transport_alignment:
    value: false
analyze_vector_averaging_alignment:
    value: true
analyze_weight_singular_values:
    value: false
barycenter_support_size:
    value: 100
batch_size:
    value: 1000
dataset_name:
    value: ColoredMNIST
device:
    value: cuda
epochs:
    value: 20000
experiment_name:
    value: ColoredMNIST_muP_run
hidden_dim:
    value: 4096
initialization_method:
    value: muP
learning_rate:
    value: 0.01
loss_function:
    value: mse
momentum:
    value: 0.9
n_neighbors_mi:
    value: 5
num_hidden_layers:
    value: 1
num_test_samples:
    value: 2000
num_train_samples:
    value: 1000
optimizer:
    value: SGD
perform_tsne_visualization:
    value: false
show_and_save_samples:
    value: true
test_correlation:
    value: 0
train_correlation:
    value: 0.8
tsne_visualization_epochs:
    value: []
use_skip_connections:
    value: false
wandb:
    value:
        enable: true
        entity: mdl-tsukuba
        project: sp_exp
